package com.example.ozgurdynamodb.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@DynamoDBTable(tableName = "TestLogs")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TestLogs {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String createDate = String.valueOf(LocalDateTime.now());

    @DynamoDBAttribute
    private String transactionId;

    @DynamoDBAttribute
    private String rawRequest;

    @DynamoDBAttribute
    private String rawResponse;
}
